### ISSUE TITLE
Bug fix request

### ISSUE THREAD

**Issue by danielgarciagarcia** [dmulloy2/Quests#2]
Hello, I've reported a bug that lots of servers are having with Quests. I would like to request a fix for it. I paste here the link where all the information is:

https://github.com/FlyingPikachu/Quests/issues/67

**Comment by charles-1** [comment]
I'd love to see this bug fixed too i have the same issue!

**Comment by danielgarciagarcia** [comment]
Is this bug going to be fixed?

**Comment by dmulloy2** [comment]
Probably not. I decided fixing this plugin would be too much, so I switched to [BetonQuest](http://dev.bukkit.org/bukkit-plugins/betonquest/), which seems to do the job well enough.
